[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../base" }
plier = {path = "../../../plier-rs"}
num-bigfloat = "1.7.1"
tokio = { version = "1.38.0", features = ["full"] }
