[basics]
env = "dev"
port = 51080
file_http="http://192.168.0.120/uploads"
file_path= "E:\\b\\files\\uploads"

[author]
username="laoniqiu"
userpwd="12345678"
penname="老泥鳅"
profile="https://avatars.githubusercontent.com/u/95899886?v=4"
introduce="web3 blog rust，服务端：rust，合约：solidity，区块链：BNB Chain"
contactMail="pandamancoin@gmail.com"

[contract]
url = "https://polygon-mainnet.infura.io/v3/d6c49b20a9bf44fabeda87029c7cf51e"
contract_address = "0x63A0B0a446800DFf71C184Ef5D4A526F49a67246"
abi_path = "web3_blog_abi.json"

[mysql_db1]
host = "41.216.181.27"
port = 53306
dbname = "test_web3_rs_blog"
username = "test_blog_u"
password = "kgd4MQD5_776dsa"
max_size = 20
max_idle = 3
connect_timeout = 50

[redis] # "redis://username:pwd@host:port/db"
username = "test_user"
pwd = "test*user77122"
host = "41.216.181.27"
port = "56379"
db = "0"

[aes]
key="0123456789abcdef0123456789abcdef"
iv="abcdef9876543210"

[reCAPTCHA] # https://developers.google.com/recaptcha/docs/display?hl=zh-cn
HTML = "6Lcn0fYpAAAAALGpkke4_lQtZEg8XqvjYlhSsb74"
SERVER = "6Lcn0fYpAAAAAEYCampr8WtStPNe8Qz2YTAkZ4Ra"
