[basics]
env = "dev"
port = 51081
file_http="http://192.168.30.12:80/uploads"
#file_http="http://testblog.wearelucky2025.top/a769x"

[mysql_db1]
host = "41.216.181.27"
port = 53306
dbname = "test_web3_rs_blog"
username = "test_blog_u"
password = "kgd4MQD5_776dsa"
max_size = 20
max_idle = 3
connect_timeout = 50

[redis] # "redis://username:pwd@host:port/db"
username = "test_user"
pwd = "test*user77122"
host = "41.216.181.27"
port = "56379"
db = "0"
size = 5

[aes]
key="an example very very secret key."
iv="unique init vect"

[reCAPTCHA]
HTML = "6Lcn0fYpAAAAALGpkke4_lQtZEg8XqvjYlhSsb74"
SERVER = "6Lcn0fYpAAAAAEYCampr8WtStPNe8Qz2YTAkZ4Ra"
