[basics]
env = "dev"
port = 51081
file_http="http://192.168.30.12:80/uploads"

[contract]
url = "https://polygon-mainnet.infura.io/v3/d6c49b20a9bf44fabeda87029c7cf51e"
contract_address = "0x63A0B0a446800DFf71C184Ef5D4A526F49a67246"
abi_path = "web3_blog_abi.json"

[coinmarketcap]
key="c031d0fd-5dfb-41e5-805d-d5dfaabe2f5f"
url="https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/latest"

[mysql_db1]
host = "2.56.116.253"
port = 13306
dbname = "blog"
username = "root"
password = "test_walqw!@#8812"
max_size = 20
max_idle = 3
connect_timeout = 50

[redis] # "redis://username:pwd@host:port/db"
username = "default"
pwd = "redis_626_240817_P"
host = "2.56.116.253"
port = "16379"
db = "1"
size = 5

[aes]
key="an example very very secret key."
iv="unique init vect"

[reCAPTCHA]
HTML = "6Lcn0fYpAAAAALGpkke4_lQtZEg8XqvjYlhSsb74"
SERVER = "6Lcn0fYpAAAAAEYCampr8WtStPNe8Qz2YTAkZ4Ra"
