[basics]
env = "dev"
port = 51081
file_http="http://192.168.30.12:80/uploads"

[mysql_db1]
host = "34.150.97.232"
port = 23306
dbname = "rs_blog"
username = "rs_blog"
password = "abcd#1890dda1"
max_size = 20
max_idle = 3
connect_timeout = 50

[aes]
key="an example very very secret key."
iv="unique init vect"

[reCAPTCHA]
HTML = "6Lcn0fYpAAAAALGpkke4_lQtZEg8XqvjYlhSsb74"
SERVER = "6Lcn0fYpAAAAAEYCampr8WtStPNe8Qz2YTAkZ4Ra"
